name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4.2.2   
    - run: npm ci
    - run: npm test
    - run: npm start &
